apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crane-cost-collector.fullname" . }}
  labels:
    {{- include "crane-cost-collector.labels" . | nindent 4 }}
data:
  config.json: |-
    {{- mustToPrettyJson .Values.config | nindent 4 }}
